apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
template:
  metadata:
    labels:
      app: frontend
      tier: web
      project: expense
  spec:
    containers:
    - name: frontend
      image: silpa11/frontend:v1
      ports:
        containerPort: 80
---
kind: service
apiVersion: v1 
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-port
    protocal: TCP
    port: 80
    targetport: 80